name:  insilichem
channels:
  - openbabel
  - omnia
  - insilichem
dependencies:
  - python=2.7.13
  - nomkl
  - certifi=2016.2.28
  - freetype=2.5.5
  - icu=54.1
  - libiconv=1.14
  - libpng=1.6.30
  - ncurses=6.0
  - numpy=1.11
  - pcre=8.39
  - readline=6.2
  - scipy=0.19
  - setuptools=27.2.0
  - sqlite=3.13.0
  - tk=8.5.18
# - nciplot
  - openbabel
  - ambermini
